// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxod6oKEIPjBk8UaVXLWeFxJ2aThOCbY4',
    appId: '1:309577948073:web:2942e588183bf1749302b8',
    messagingSenderId: '309577948073',
    projectId: 'flutter-chatapp-58fa0',
    authDomain: 'flutter-chatapp-58fa0.firebaseapp.com',
    storageBucket: 'flutter-chatapp-58fa0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg9oTyKrOg3h9ovmm5iMv8RJ1nJT9M4qo',
    appId: '1:309577948073:android:a181f2ba1f0e609c9302b8',
    messagingSenderId: '309577948073',
    projectId: 'flutter-chatapp-58fa0',
    storageBucket: 'flutter-chatapp-58fa0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtk0JDbWAcC8RhgyAHJqyW42Rszz1-Vow',
    appId: '1:309577948073:ios:9c0dbee2bf8f65709302b8',
    messagingSenderId: '309577948073',
    projectId: 'flutter-chatapp-58fa0',
    storageBucket: 'flutter-chatapp-58fa0.firebasestorage.app',
    iosBundleId: 'com.example.section14Chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtk0JDbWAcC8RhgyAHJqyW42Rszz1-Vow',
    appId: '1:309577948073:ios:9c0dbee2bf8f65709302b8',
    messagingSenderId: '309577948073',
    projectId: 'flutter-chatapp-58fa0',
    storageBucket: 'flutter-chatapp-58fa0.firebasestorage.app',
    iosBundleId: 'com.example.section14Chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxod6oKEIPjBk8UaVXLWeFxJ2aThOCbY4',
    appId: '1:309577948073:web:1812ac49193ff66e9302b8',
    messagingSenderId: '309577948073',
    projectId: 'flutter-chatapp-58fa0',
    authDomain: 'flutter-chatapp-58fa0.firebaseapp.com',
    storageBucket: 'flutter-chatapp-58fa0.firebasestorage.app',
  );

}